services:
  - type: web
    name: learning-chinese-backend
    env: node
    region: singapore
    rootDir: backend
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEB_APP_URL
        value: https://learning-chinese-five.vercel.app
